CREATE TABLE IF NOT EXISTS guilds(id TEXT PRIMARY KEY, name TEXT);
CREATE TABLE IF NOT EXISTS bots(id TEXT PRIMARY KEY, manifest_hash TEXT);
CREATE TABLE IF NOT EXISTS features(id TEXT PRIMARY KEY, owner_bot TEXT);
CREATE TABLE IF NOT EXISTS platform_modules(id TEXT PRIMARY KEY, version TEXT);
CREATE TABLE IF NOT EXISTS modules(id TEXT PRIMARY KEY, module_type TEXT);
CREATE TABLE IF NOT EXISTS capabilities(id TEXT PRIMARY KEY, namespace TEXT);
CREATE TABLE IF NOT EXISTS capability_grants(id TEXT PRIMARY KEY, capability_id TEXT, scope TEXT, effect TEXT);
CREATE TABLE IF NOT EXISTS config_profiles(id TEXT PRIMARY KEY, name TEXT);
CREATE TABLE IF NOT EXISTS config_values(id TEXT PRIMARY KEY, profile_id TEXT, key TEXT, value TEXT);
CREATE TABLE IF NOT EXISTS staged_config_values(id TEXT PRIMARY KEY, profile_id TEXT, key TEXT, value TEXT);
CREATE TABLE IF NOT EXISTS audit_events(id TEXT PRIMARY KEY, ts TEXT, actor TEXT, actor_type TEXT, guild_id TEXT, module_id TEXT, action_type TEXT, target TEXT, before_after_summary TEXT, correlation_id TEXT, result TEXT, reason TEXT, evidence_case_id TEXT);
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY, job_type TEXT, state TEXT);
CREATE TABLE IF NOT EXISTS module_builds(id TEXT PRIMARY KEY, module_id TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS module_updates(id TEXT PRIMARY KEY, module_id TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS platform_status(id TEXT PRIMARY KEY, platform_id TEXT, health TEXT);
CREATE TABLE IF NOT EXISTS dashboard_status(id TEXT PRIMARY KEY, key TEXT, value TEXT);
CREATE TABLE IF NOT EXISTS evidence_cases(id TEXT PRIMARY KEY, status TEXT);
CREATE TABLE IF NOT EXISTS evidence_items(id TEXT PRIMARY KEY, case_id TEXT, hash TEXT);
CREATE TABLE IF NOT EXISTS evidence_access_log(id TEXT PRIMARY KEY, case_id TEXT, actor TEXT, ts TEXT);
CREATE TABLE IF NOT EXISTS verification_cases(id TEXT PRIMARY KEY, user_id TEXT, risk_score INTEGER);
CREATE TABLE IF NOT EXISTS verification_challenges(id TEXT PRIMARY KEY, case_id TEXT, challenge_type TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS vouches(id TEXT PRIMARY KEY, case_id TEXT, vouched_by TEXT);
CREATE TABLE IF NOT EXISTS moderation_cases(id TEXT PRIMARY KEY, guild_id TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS appeals(id TEXT PRIMARY KEY, moderation_case_id TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS modmail_threads(id TEXT PRIMARY KEY, guild_id TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS tickets(id TEXT PRIMARY KEY, guild_id TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS user_notes(id TEXT PRIMARY KEY, user_id TEXT, note TEXT);
CREATE TABLE IF NOT EXISTS risk_scores(id TEXT PRIMARY KEY, user_id TEXT, score INTEGER);
CREATE TABLE IF NOT EXISTS analytics_events(id TEXT PRIMARY KEY, ts TEXT, event_type TEXT, payload TEXT);
